### PR TITLE
`restore-file` - fix(restore-file): use conventional commit

### PR DESCRIPTION
**Pull request by skjnldsv**
https://www.conventionalcommits.org

### CODE REVIEW

**Comment by fregante** [comment]
Thanks but I'd rather not

**Comment by skjnldsv** [comment]
@fregante why not? :)

**Comment by fregante** [comment]
It's just one of many conventions, I don't think I've ever contribute to more than 3 projects with that conventions ever.

**Comment by skjnldsv** [comment]
Ah, too bad!
Many popular tools now supports it.
Dependabot, renovate... etc

**Pull request closed without merging**
