### PR TITLE
`closing-remarks` - Exclude nightly tags and non-version tags

### PR DESCRIPTION
**Pull request by fregante**
- Fixes https://github.com/refined-github/refined-github/issues/7206

## Test URLs

- Junk tag: https://github.com/refined-github/sandbox/pull/1
	- See: https://github.com/refined-github/sandbox/branch_commits/f743c334f6475021ef133591b587bc282c0cf4c4
	- Screenshot 9
- Normal tag: https://togithub.com/refined-github/refined-github/pull/7127
	- See https://github.com/refined-github/refined-github/branch_commits/5321825
	- Screenshot 8
- Nightly tag: https://togithub.com/neovim/neovim/pull/22060
	- see: https://github.com/neovim/neovim/branch_commits/27b81af
	- Screenshot 5

### CODE REVIEW

**Comment by wookayin** [comment]
Thank you very much for positively considering this! Yes, that specific commit isn't released yet so I think that'd be a correct behavior.

**Comment by fregante** [comment]
> that specific commit isn't released yet

Are you sure? That commit is 4 months old and is on `master`.

**Comment by jmcarcell** [comment]
Can someone explain what is needed for the message "This pull request first appeared in 24.2.2" to appear? Does one need to make a release from Github? In some other repositories I don't see these messages even though there is certainly a tag that has them.

**Comment by fregante** [comment]
When you merge a PR, GitHub creates a commit. You can see the commit hash in the event immediately following the merge. 

Refined GitHub asks GitHub if this commit appears in any tags. 

If it doesn't work in some repos, it's probably because they create a tag from another branch (e.g. "git flow" method). Also it might just be a Refined GitHub cache issue

**Pull request merged**
