### PR TITLE
Added brave icon

### PR DESCRIPTION
**Pull request by jerskisnow**
This PR only contains an extra image in the README indicating that the chrome extension is also supported for Brave, because brave is worthy of being mentioned alongside opera and edge.

### CODE REVIEW

**Comment by cheap-glitch** [comment]
Duplicate of #4300 and #5041.

**Comment by kidonng** [comment]
I don't know if this happened to be created just after #5041 but maybe revising the README would reduce confusion:

```diff
- also compatible with <Edge icon> <Opera icon>
+ also compatible with Chromium-based browsers
```

@refined-github/maintainers thoughts?

**Comment by cheap-glitch** [comment]
Maybe
```
also compatible with <Edge icon> <Opera icon> and other Chromium-based browsers
```

**Comment by fregante** [comment]
> would reduce confusion

I don't think it would reduce the amount of PRs nor the requests to "add support for Edge"

**Comment by kidonng** [comment]
The issue I see is not that people know no background about their browsers, it's that we list _some_ Chromium-based ones. So I suggest we just list none.

**Comment by fregante** [comment]
> I suggest we just list Chrome only.

I'd prefer that honestly, I just noticed that those logos stopped the requests/PRs for Edge/Opera. There are other browsers but their usage/recognition is minimal. I mean, heck, Brave is at 0.05%, which is 2% of Opera’s usage, which itself is 2% of the global. https://kinsta.com/browser-market-share/

**Pull request closed without merging**
