### PR TITLE
Add browser icon to version badges

### PR DESCRIPTION
**Pull request by salmanulfarzy**
Shields recently added support for [simple-icons](https://simpleicons.org) for using various icons on badges.

### Before

Without browser icon

### After

Browser icon with description

<details>
<summary>Alternate: Just add icon to badge without modifying the labels</summary>

Browser icon only

</details>

### CODE REVIEW

**Comment by bfred-it** [comment]
On OSX for comparison: 

screen shot 2018-09-18 at 17 30 52

It doesn't _look_ too bad, but it no longer looks like an actionable item. Badges are usually "see and forget", not the main CTA

**Comment by salmanulfarzy** [comment]
How about the alternate version with just the browser icons without any labels and keeping the existing text ? 

I'll update the PR if that looks okay.

**Comment by bfred-it** [comment]
The icon spacing is off 😃

**Comment by salmanulfarzy** [comment]
Badge labels are kept as empty space like current behavior. Leaving it blank would fallback to default labels (`mozilla add-on`/`chrome web store`) . Specifying browser/store names was too long, May be abbreviated form of store names like  `AMO` and `CWS` as badge labels ?

**Comment by bfred-it** [comment]
I don’t think any of this adds anything

**Pull request closed without merging**
