### PR TITLE
Don't change `sticky-sidebar` state while interacting with it

### PR DESCRIPTION
**Pull request by fregante**
- Closes https://github.com/refined-github/refined-github/issues/5939

## Test URLs

- this PR
- the repo home

To actually test it, you'd have to try on a repo with projects, as shown in the original issue

### CODE REVIEW

**Comment by fregante** [comment]
cc @janpio

**Comment by janpio** [comment]
(Is there a simple way to test from a PR? Happy to help out testing this.)

**Comment by fregante** [comment]
I don't know how simple it is, but you can look on contributing.md or in the wiki for instructions on how to run it

**Comment by yakov116** [comment]
@fregante did we remove the artifact? I tried looking for it to give to @janpio but was unable to find it

**Comment by fregante** [comment]
Yes I did in https://github.com/refined-github/refined-github/pull/5799/files because I didn't think about this possibility 😅 it can be restored

**Comment by janpio** [comment]
That was exactly what I spent a few minutes looking for. Checking out and building locally is usually too much hassle.

**Comment by fregante** [comment]
You can now find it on the Actions/Test page:

https://github.com/refined-github/refined-github/actions/runs/3044209088

Or for the direct zip link: https://github.com/refined-github/refined-github/suites/8264307360/artifacts/361603861

**Comment by janpio** [comment]
I can confirm that when clicking "+7 more" in the sidebar on https://github.com/janpio/refined-github-sticky-sidebar-projects-bug/issues/1 does indeed not instantly move the expanded sidebar to the top out of my viewport 👍 

It still does happen as soon as I move my mouse outside of the sidebar area though - not sure if that is expected. (If I keep my mouse on the sidebar, scrolling to top and bottom of the issue behave pretty ok to me.)

**Comment by janpio** [comment]
Uh, I just noticed that the "cog" icon next to "Milestone" or "Projects" etc does not work with the version I tested ("Labels" and "Assignees" still works). No error message in console or similar. Is that a possible side effect? Or something else broken in `main`?

**Comment by fregante** [comment]
It's most likely https://github.com/refined-github/refined-github/issues/5843. We already disabled the feature via [yolo](https://github.com/refined-github/yolo), but it doesn't apply to developer versions (v0.0.0)

**Comment by janpio** [comment]
Thanks for that context.

**Pull request merged**
