### PR TITLE
Restore padding broken by `scrollable-code-and-blockquote`

### LINKED ISSUE #5540: `scrollable-code-and-blockquote` mistakenly removes code block padding
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/sveltejs/language-tools/issues/1418

(just find some issue with no-highlight pre elements)

### Extension version

22.3.18

### Browser(s) used

Chrome 99.0.4844.74 (x86_64) on MacOS 12.3

### Description

Just look at the code block in that issue, the padding-bottom was shorten

Snipaste_2022-03-22_14-11-34

because scrollable-code-and-blockquote defined&hellip;

```css
:root .comment-body :is(blockquote, pre) { padding-bottom: 0.2em }
```

&hellip;which is more specific than GitHub's

```css
.markdown-body pre { padding: 16px }
```

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by kidonng**
Fix #5540

## Test URLs

Copied from #5509 (which caused this bug)

- https://github.com//refined-github/refined-github/pull/5416#issuecomment-1041546190
- https://github.com//discordjs/discord.js/pull/6162#issuecomment-884157859
- https://github.com//refined-github/refined-github/pull/5506#issuecomment-1067652695

### CODE REVIEW

**Comment by fregante** [comment]
Doesn't this cause #4597?

**Comment by kidonng** [comment]
> Completely unrelated to RG…

It's a screenshot of code blocks and not error message of Refined GitHub, though I could have added a better one.

**Comment by fregante** [comment]
Oh sorry about that, my sleepy brain saw it as a “console error” section 🤦‍♂️

**Comment by cheap-glitch** [comment]
@kidonng Is there anything left to do on this PR?

**Comment by fregante** [comment]
I'd be great to also have a hotfix for the 2 current versions

**Pull request merged**
