### PR TITLE
`scrollable-areas` - Remove from new commit conversation view

### LINKED ISSUE #8099: `scrollable-areas`: scrollbar doesn't stick to the right in markdown file's code blocks
### Description

Take a look at the code blocks in the README here: https://github.com/elastio/bon#struct-builder. The scroll bars appear in the middle of the block. I think they stick to the widest code line in that block.

image

### How to replicate the issue + URL

Take a look at the README in https://github.com/elastio/bon#struct-builder

### Extension version

24.11.21

### Browser(s) used

Chrome v131.0.6778.86 (Official Build) (64-bit)

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

### PR DESCRIPTION
**Pull request by kovsu**
- Fixes #8099 

## Test URLs

- https://github.com/elastio/bon#struct-builder
- https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2

## Screenshot

image

### CODE REVIEW

**Comment by kovsu** [comment]
image

**Comment by kovsu** [comment]
Why the scroll bar looks so unsightly now.

**Comment by kovsu** [comment]
|  CleanShot 2024-11-24 at 01 19 45@2x | CleanShot 2024-11-24 at 01 20 23@2x |
| --- | --- |

**Comment by fregante** [comment]
I think it's just a rendering bug, it works fine for me

Screenshot

**Review by fregante — APPROVED** [review]

**Pull request merged**
