### PR TITLE
Fix `one-click-pr-or-gist` private free repos pr creation

### LINKED ISSUE #6391: `one-click-pr-or-gist` is broken in free private repos
### Description

As you can see, in free private repo, the button has changed to do the promotion of Draft PR that offers paid plans.
> 

### How to replicate the issue + URL

This rule can not be respected because GitHub just changed the design for PRIVATE repositories (with free plan only).

Public repo
> 

Any private repo (in free plan)
> 

### Steps

1. Go to any private repo with a free plan
2. Go to pull requests
3. Click on the "New Pull Request" green button
4. Select a mergeable branch
5. Click on the "New Pull Request" green button

### Extension version

23.2.20

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by DraftProducts**
Closes #6391

This page affects PR creation in private repos

## Screenshot

Without the fix
> 

With the fix
>

### CODE REVIEW

**Comment by yakov116** [comment]
It would be better to check if the "unable to create draft" button exists. Since now if the dom changes at any point we won't see any errors

**Comment by fregante** [comment]
I think that we just want to leave the drop-down untouched in that case. 

Can you craft a selector for that "teams" label and add it as a function in the `exclude` array? Find "exclude" on https://github.com/refined-github/refined-github/blob/main/contributing.md#featuresadd for more info

**Comment by DraftProducts** [comment]
Hi @fregante 👋 
I'd like to propose an alternative rather than disabling this feature.
If the goal is to keep promoting GitHub for its paid plan, couldn't we just recreate a button next to it that would continue to open the promotion modal? Adding the attribute `data-show-dialog-id="drafts-upgrade-dialog"` to any button would open it.

**Comment by fregante** [comment]
No, there's no point in keeping the feature enabled for a button that doesn't work.

We can't hide it (as in your original screenshot) and we should not hide the inline documentation/explanation. So leaving it alone is the easiest thing to do (also because there will be no one around to fix it when it breaks)

**Review by fregante — APPROVED** [review]
Thank you, excellent! 💚

**Review by CyberFlameGO — APPROVED** [review]
LGTM!

**Review by fregante — APPROVED** [review]
Perfect it works, thank you!

**Pull request merged**
