### PR TITLE
Minor tweaks to Safari extension app

### PR DESCRIPTION
**Pull request by sindresorhus**
Just simplifying the Xcode project at little bit (one extension target instead of two).

### CODE REVIEW

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Did you already submit it to the App Store? If not, wait 😃

**Comment by fregante** [comment]
CI started failing: https://github.com/refined-github/refined-github/actions/runs/6244192317/job/16950762626

```
Switching Xcode to version '15.0-beta'...
Available versions:
┌─────────┬──────────┬─────────────┬─────────────┬────────┬────────────────────────────────┐
│ (index) │ version  │ buildNumber │ releaseType │ stable │              path              │
├─────────┼──────────┼─────────────┼─────────────┼────────┼────────────────────────────────┤
│    0    │ '14.3.0' │  '14E222b'  │    'GM'     │  true  │ '/Applications/Xcode_14.3.app' │
│    1    │ '14.2.0' │   '14C18'   │    'GM'     │  true  │ '/Applications/Xcode_14.2.app' │
│    2    │ '14.1.0' │  '14B47b'   │    'GM'     │  true  │ '/Applications/Xcode_14.1.app' │
└─────────┴──────────┴─────────────┴─────────────┴────────┴────────────────────────────────┘
Error: Could not find Xcode version that satisfied version spec: '15.0-beta'
```

**Comment by sindresorhus** [comment]
It says it's available here: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

The testing here as limited use since I already test locally, so I suggest just disabling this test until GitHub properly updates Xcode.

**Comment by fregante** [comment]
Yeah it worked for a while and now it seems to fail. I can still merge the PRs even if they fail for now. Let's see how long it lasts

**Pull request merged**
