### PR TITLE
Avoid "Permission needed" bug on Firefox for now

### LINKED ISSUE #7477: Extension demands access on all websites (Firefox)
### Description

Using Firefox, after 24.6.21 update the extension demands access on all websites. I guess it's the Manifest V3 thing?

image
image

### How to replicate the issue + URL

1. Open any unrelated website.
2. Observe the extension icon.

### Extension version

24.6.21

### Browser(s) used

Firefox 127.0.1

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #7477 
- Related https://github.com/refined-github/refined-github/pull/7480

This should work, assuming AMO doesn't block manifest downgrades.

The manifest.json in `source` will continue to work in both browsers.

cc @INSANEMODE @HanabishiRecca

### CODE REVIEW

**Comment by HanabishiRecca** [comment]
> This should work, assuming AMO doesn't block manifest downgrades.

Hmm, there is something strange happening. Seems like FF doesn't switch on the fly.

Also
```
Reading manifest: Warning processing background.service_worker: An unexpected property was found in the WebExtension manifest.
```
```
Reading manifest: Warning processing $schema: An unexpected property was found in the WebExtension manifest.
```
```
Reading manifest: Warning processing optional_host_permissions: An unexpected property was found in the WebExtension manifest.
```

**Comment by HanabishiRecca** [comment]
And it doesn't help anyway. The notification is still there.

**Comment by fregante** [comment]
You're testing the regular extension, this cleanup needs to be run manually locally. You have to run the new `npm run manifest distribution 2` script to enable it.

This is done automatically in the release workflow when a new version is released.

**Comment by HanabishiRecca** [comment]
I see. Yeah, it works now.

**Pull request merged**
