### PR TITLE
Remove issue "May be fixed by" in `clean-conversation-headers`

### PR DESCRIPTION
**Pull request by kidonng**
This info is available in the sidebar:

截屏2021-12-02 21 56 53

## Test URLs

https://togithub.com/refined-github/refined-github/issues/4952

## Screenshot
Before:
image

After:

image

### CODE REVIEW

**Comment by fregante** [comment]
I'm not sure I like deprioritize this piece of information, which is pretty important when looking at an issue. The header is *always* visible

**Comment by kidonng** [comment]
I have conflicted thoughts about this too. I forgot to mention another thing that made me do this PR: the PR header doesn't have this "May be fixed by" link, only "Linked issues".

I would like to align issues with PR, since the latter cannot be changed I just removed the former from issues. How about we add something like "May fix #number" to PR header instead?

**Comment by cheap-glitch** [comment]
> How about we add something like "May fix #number" to PR header instead?

Feels redundant to me, there's a good chance it's mentioned in the first post with a `Fixes #1234`, and it's in the sidebar too.

**Comment by fregante** [comment]
> How about we add something like "May fix #number" to PR header instead?

We had a feature like this before GH added "may be fixed by". I'm -0 on this now though

**Comment by fregante** [comment]
I'd rather not

**Pull request closed without merging**
