### PR TITLE
Update App Store icon

### PR DESCRIPTION
**Pull request by fregante**
@sindresorhus does a palette inversion quench your refresh thirst? 😃 

Before | After
--- | ---
 | 

Making the icon completely flat white could also work, similar style to GitHub Desktop’s:

### CODE REVIEW

**Comment by sindresorhus** [comment]
Not a big fan. The gradient clashes with the artwork.

**Comment by fregante** [comment]
(inner shadow would be better probably)

Before | After
--- | ---
 | AppIcon

**Comment by fregante** [comment]
Inner shadow

Before | After
--- | ---
 | AppIcon2

**Comment by sindresorhus** [comment]
I'm fine with just keeping the existing icon.

**Pull request closed without merging**
