### PR TITLE
Restore `center-reactions-popup` feature

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fix https://github.com/refined-github/refined-github/issues/5881

## Test URLs

- This page
- [Split view with review comments](https://github.com/refined-github/sandbox/pull/38/files?diff=split)

## Screenshots

**Regular comment**

image

**Review comment in split diff view**

image

### CODE REVIEW

**Review by cheap-glitch — COMMENTED** [review]
Dropped a lot of code since the feature is 3~4 years old and most of it is outdated.

**Comment by fregante** [comment]
Could you also add a width on the popup so they wrap like they used to? I feel that the single line is the most annoying part. 

I fully expect them to add an emoji picker this year though, it feels like that's the reason why they changed the layout now. But… we can hotfix it if/when that happens.

**Review by cheap-glitch — COMMENTED** [review]
Completely dropped the positioning fix for right-side comments in split diff view, since the two-line layout makes the popup smaller and it never gets clipped, even on smaller screens.

**Comment by fregante** [comment]
It's being overridden by `.d-flex`

Screen Shot

**Comment by cheap-glitch** [comment]
Fixed and tested on Chromium:

image

**Review by fregante — APPROVED** [review]

**Pull request merged**
