### PR TITLE
Drop newsfeed-related feature 

### PR DESCRIPTION
**Pull request by fregante**
The feed is gone. Time to drop a few features? 

It also has a filter so probably this config will cover what our features did before:

Screenshot 2

Note: The title uses "feature" in order to appear in the readme link:

- https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Amerged+-label%3Ameta+in%3Atitle+drop+feature

### CODE REVIEW

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/issues/6884

**Review by yakov116 — APPROVED** [review]

**Comment by port19x** [comment]
So the issue with the new feed is that it largely presents content unrelated to the people you follow.
That feed is still natively accessible through @dashboard-feed, but at the loss of the other sidebars.
Community outrage is rather large, as the new feed is nigh-useless for users that previously used this to retrieve software-recommendations, by observing stars of followed users.

I guess it's a good idea to drop features of the old feed first.
Should I make another issue for this?

**Review by port19x — APPROVED** [review]

**Comment by port19x** [comment]
> > So the issue with the new feed is that it largely presents content unrelated to the people you follow.
> 
> See the config I screenshotted: it only shows people I follow. That's it.
> 
> Also see [#6890 (comment)](https://github.com/refined-github/refined-github/issues/6890#issuecomment-1711127133)

That's definitely a coincidence and/or shaped by your usage of github.
I'm getting stars from people I sponsored with 1 USD two years ago, as well as repo authors of one of the ~100 stars I have.
Filtering the "event type" is possible and works, but the "event origin" is out of our agency

**Comment by fregante** [comment]
Let's see how it evolves, we can certainly reintroduce `hide-newsfeed-noise` if it's still applicable. I'm not going to merge this PR just yet

**Comment by fregante** [comment]
Closing for now, we can review it in a few months

**Pull request closed without merging**
