### PR TITLE
Fix CSS features disappearing after clicking on a link

### LINKED ISSUE #5719: Nothing works until you refresh the page (Ajax issue)
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

Everywhere

### Extension version

22.5.22

### Browser(s) used

Safari

### Description

I keep noticing more and more features are missing until I refresh the page. Example:

1. Visit https://github.com/refined-github/refined-github
2. Open a folder
3. Notice lack of `ci-link`, `rgh-linkify-features`, `quick-file-edit`,  `clean-repo-tabs`, etc

https://user-images.githubusercontent.com/1402241/175481173-960b33f1-f928-43d7-ab5e-2a594c84e261.mov

Interestingly I found the `New Issue` textareas to not turn into rich text editors sometimes (GitHub issue)

before

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by fregante**
- Maybe closes #5719 ?
- Potentially also mentioned in https://github.com/refined-github/refined-github/pull/5720#issuecomment-1167966280

## Test URLs

1. Open https://github.com/refined-github/refined-github/issues
3. Click on Issues tab

## Before

https://user-images.githubusercontent.com/1402241/176489932-20874707-d01b-4234-aa1f-fee4da581eea.mov

## After

https://user-images.githubusercontent.com/1402241/176490087-90b92331-a8f3-4f01-b167-017334003e32.mov

### CODE REVIEW

**Comment by yakov116** [comment]
Working for me but has a noticeable jump

**Comment by fregante** [comment]
I've been noticing that jump too, but only sometimes (in a Safari window I always get a jump on reload, but on the other window I do not 😰).

Either way it's unrelated to this specific issue and we should probably open a new issue for that if it persists. The only reason why it could be happening is in `globalReady` (or due to an unavoidable browser restriction/bug)

**Comment by fregante** [comment]
ha!

**Comment by yakov116** [comment]
RAAA LOL

**Comment by fregante** [comment]
> ```js
>  await waitFor(() => document.body); 
> ```

That's potentially the issue, but it's not really something new or anything that GitHub or us can affect, that's the weird part.

We can replace it with an `observeElement(document.documentElement)`, assuming that it _always_ exists (can we assume that?)

**Comment by yakov116** [comment]
I forgot already how did we land up with document.body? I would want to check in history why we did not use observe element.

**Comment by fregante** [comment]
> I forgot already how did we land up with document.body?

The content scripts are injected on `document_start`, which may happen before the document is parsed. This means that the script might find an empty page so we have to wait for it. We use to have `requestAnimationFrame` to catch the first draw, but that means we can't do anything until the tab becomes visible, even if it loaded a minute ago.

Maybe we can combine the two in a race:


```js
await Promise.race([
	frame(),
	waitFor(() => document.body)
])
```

**Comment by yakov116** [comment]
If I am not mistaken, requesting the frame broke Firefox. (GitHub froze)

**Review by cheap-glitch — APPROVED** [review]
Working on Firefox, but it is somewhat slower than before.

**Comment by cheap-glitch** [comment]
Btw there's still some `document.body.classList` calls in https://github.com/refined-github/refined-github/blob/main/safari/Shared%20(App)/Resources/Script.js, not sure if those should be updated too.

**Comment by fregante** [comment]
That’s a web view in the native app.

**Pull request merged**
