### PR TITLE
Fix `sticky-file-header` on commits

### PR DESCRIPTION
**Pull request by kidonng**
Broken by GitHub's Pull Request File Tree feature added a while ago.

## Test URLs

https://github.com/refined-github/refined-github/commit/1d9dd9f0208c327351512beb6d6a22279bc47807

## Screenshot

https://user-images.githubusercontent.com/44045911/175102994-8b4e0eb2-1229-4d26-bc69-28f2c67cc995.mov

---

I would really like to add https://github.com/kidonng/cherry/commit/997ccdf5bd36f4f888622d5c5a06426da81509ab as well, since that's pretty much the only place left with no sticky file header (and technically speaking, GitHub already enabled it for markup i.e. Markdown files).

---

P.S. it's funny GitHUb pushed a bug when I'm working on this

image

### CODE REVIEW

**Review by fregante — APPROVED** [review]
Seems right. Can you also hotfix it?

**Comment by kidonng** [comment]
That component has no shadow indeed. The shadow on PRs comes from a standalone component `.toolbar-shadow`. Here is my take to replicate this shadow:

```css
.pr-toolbar.is-stuck {
    box-shadow: 0 2px 2px rgba(0, 0, 0, 0.075);
    border-bottom: 1px solid rgba(0,0,0,.15)
}
```

**Comment by fregante** [comment]
> The only problem is that there's no border between the two headers:

GitHub does the same on `PRFiles` too. PR welcome to improve the style globally, but it's otherwise `not-a-bug`

**Comment by ncfavier** [comment]
`top: 60px` breaks gists:

**Comment by kidonng** [comment]
@ncfavier #5732

**Comment by ncfavier** [comment]
This is still not fixed for me on 22.7.11.

**Comment by ncfavier** [comment]
Never mind, I'm still on 22.6.25. Firefox was displaying the version as 22.7.11 before restarting, something wrong with hotfixing maybe?

**Pull request merged**
