### PR TITLE
Restore `user-local-time`

### LINKED ISSUE #5699: `user-local-time` not working
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github

### Extension version

22.5.22

### Browser(s) used

Brave Version 1.39.122 Chromium: 102.0.5005.115 (Official Build) (arm64)

### Description

The user local timezone isn't shown anymore in the hover card.
Not sure if it was broken before, I only noticed it now.

From what I could see the feature hasn't been removed.

CleanShot 2022-06-17 at 13 30 19@2x

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by mangkoran**
- Closes #5699

## Test URLs

(In case its you that viewing the PR, I put several accounts here)
- @fregante (sorry for the ping)
- @yakov116 (sorry for the ping)
- @mangkoran

## Screenshot
image

### CODE REVIEW

**Comment by mangkoran** [comment]
A bit out of context, but how this feature works? Sometimes I can see the local time, sometimes not (disregarding this issue)?

**Review by fregante — APPROVED** [review]
## Mantap!

**Comment by fregante** [comment]
I confirm it works:

Screen Shot



> how this feature works

Commits include your timezone, so we fetch the user’s "github event" until we find the latest commit. If a user hasn't pushed in a while or hasn't pushed at all, the feature won't work.

**Comment by yakov116** [comment]
Will this break GHE?

**Comment by mangkoran** [comment]
Thank you for amending. I have no idea it will break GHE (I have no idea that GHE is different either). Glad to be able to contribute to RGH :D

**Comment by cheap-glitch** [comment]
> I have no idea that GHE is different either

GHE = GitHub Enterprise. If I'm not wrong it's basically separate versions of GitHub that run on private company servers, which means they're always lagging behind in term of updates. So we also have to support (up to a point) "older versions" of GitHub.

> Glad to be able to contribute to RGH

Thank you for your help! We have a bunch of easy issues if you feel like contributing again :wink:

https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22

**Pull request merged**
