### PR TITLE
`netiquette` - Hide banners in preview tab

### LINKED ISSUE #7612: `netiquette` appears in preview tab
### Description

c

### How to replicate the issue + URL

https://github.com/facebook/react/pull/19377

### Extension version

24.7.29

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by kidonng**
Fix #7612

## Test URLs

- Draft PR: https://github.com//refined-github/sandbox/pull/7
- Old PR: https://github.com//facebook/react/pull/209

## Screenshot

`draft-pr-notice`

https://github.com/user-attachments/assets/840956f9-6427-4823-a2eb-a502c4be0df8

`netiquette`

https://github.com/user-attachments/assets/0c63ad0c-8a89-49d6-bfba-0701277517de

### CODE REVIEW

**Comment by fregante** [comment]
Should we just merge the two features? 🤔

**Comment by kidonng** [comment]
That was my first thought when I made #7514 but I put it off so we can have something usable first. I have no issue if you agree to merge them.

**Comment by fregante** [comment]
The last rename was just a week ago https://github.com/refined-github/refined-github/pull/7570 and the feature wasn't mentioned anywhere else I think. Perfect time to roll it into netiquette and treat it as another rename.

**Comment by fregante** [comment]
You can merge them here and update the description. I'll take care of a unified screenshot once we settle on better wording for the "highly active" version.

**Comment by fregante** [comment]
I'll merge them later together with the screenshot 🙏 

I wanted to merge this as a bugfix first so it appears in the release notes.

**Pull request merged**
