### PR TITLE
Fix handling of slashed branches in some commits list features

### LINKED ISSUE #4196: `follow-file-renames` should handle branch names with slashes, but doesn't
https://github.com/sindresorhus/refined-github/commits/Slash/slash?after=ee8b6422d2ddd1199f557594d03e7ee850e843f0+34&branch=Slash%2Fslash&path%5B%5D=webpack.config.ts

As a consequence of recent changes outlined in #4179 and fixed in #4193, slashed branches are not currently supported in commits pages. 

#4187 might fix it.

Follows #4193

### LINKED ISSUE #4492: Branches with multiple slashes aren't fully supported
1. https://github.com/yakov116/TestR/tree/this/branch%2Fhas%2Fmany%2Fslashes
2. 
스크린샷 2021-06-18 오후 6 15 15

3. 
스크린샷 2021-06-18 오후 6 13 51

The problem found from https://github.com/sindresorhus/refined-github/pull/4474
this is a task afterwards https://github.com/sindresorhus/refined-github/pull/4474

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #4492
Fixes #4196

## Test URLs

 * [Branch commits list](https://togithub.com/refined-github/sandbox/commits/branch/with/slashes)
 * [Renamed file history](https://togithub.com/refined-github/sandbox/commits/branch/with/slashes/renamed.md)

## Screenshot

`follow-file-renames`

image

`list-prs-for-branch`

image

### CODE REVIEW

**Comment by yakov116** [comment]
@cheap-glitch don't forget to remove

https://github.com/refined-github/refined-github/blob/1fd3bbb39a5e5eea712a7973fac1faa6ff5fef66/source/features/list-prs-for-branch.tsx#L18

**Comment by fregante** [comment]
If it fixes a bug in a feature it's not meta

**Comment by fregante** [comment]
``` 
  s   t o
  h
t i m e
  0
```

**Comment by yakov116** [comment]
@cheap-glitch your the best!!

**Pull request merged**
