### PR TITLE
Fix repository avatar misalignment

### PR DESCRIPTION
**Pull request by Agreon**
## Test URLs
https://github.com/refined-github/refined-github

### Without fix:

Screenshot from 2022-07-08 14-36-24

Screenshot from 2022-07-08 14-36-05

### With fix:
Screenshot from 2022-07-08 14-45-02

Screenshot from 2022-07-08 14-45-25

### CODE REVIEW

**Review by fregante — APPROVED** [review]
Thank you! Can you also send a PR to https://github.com/refined-github/yolo ?

It needs to create `style/22.7.7.css` with the equivalent CSS and selector to hotfix it on 22.7.7. 

No worries if you have no time

**Comment by kidonng** [comment]
I don't see any misalignment here. Here's how it looks _after_ adding `.flex-self-stretch`:

image

**Review by fregante — CHANGES_REQUESTED** [review]
Indeed I'm not seeing any here either. I just now tested in Chrome and Firefox. 

Screen Shot

Are you using any extensions?

**Comment by Agreon** [comment]
No i don't use any other extensions :thinking:

**Comment by Agreon** [comment]
@kidonng I guess it depends a little bit on whether a username contains uppercase characters. I published another commit ;)

**Comment by fregante** [comment]
> whether a username contains uppercase characters.

No:

Screen Shot 9


That doesn't appear to be the case from your very first screenshots either.

The only misalignment I see is related to https://github.com/refined-github/refined-github/pull/5623:

Screen Shot 8

Native:

Screen Shot 7

**Comment by fregante** [comment]
Do you have any extra stylesheets, any custom CSS or any disabled features?

**Comment by Agreon** [comment]
Hm okay, i cannot reproduce it on my chrome either. But i installed the latest Firefox developer version and it also has my issue :sweat_smile: Maybe it's my OS (just ubuntu) or something... But I'd say nevermind. Seems to be an issue just for me.

**Comment by fregante** [comment]
Basically a duplicate of https://github.com/refined-github/refined-github/issues/5247

**Comment by fregante** [comment]
You can keep the CSS in your Custom CSS box to fix it on Firefox 👍

**Pull request closed without merging**
