### PR TITLE
Adds `C-bug` to supported labels

### PR DESCRIPTION
**Pull request by Milo123459**
## Test URLs

https://github.com/rust-lang/rust

### CODE REVIEW

**Comment by busches** [comment]
At this point should we just make it a regex where anything `-bug` would match?

Also, are there other projects that use this label? Or is C short for confirmed or C the language?

**Comment by Milo123459** [comment]
Rust-analyser uses it, along with every repo under the rust-lang org.

**Review by fregante — CHANGES_REQUESTED** [review]
We're definitely not adding niche labels or else everyone will want its own. 

We didn't initially add just -bug because there might be not-a-bug labels

**Comment by yakov116** [comment]
I think we support enough edge cases. This is sort of custom already.

**Comment by kidonng** [comment]
> We didn't initially add just -bug because there might be not-a-bug labels

I think this should be the other around: we probably want to include every label that matches "bug" _then_ exclude false positives (e.g. `not-a-bug`).

**Comment by Milo123459** [comment]
This label is used a lot, but I understand where you are coming from.

**Comment by fregante** [comment]
@kidonng can do

**Pull request closed without merging**
