### PR TITLE
`reactions-avatars` - Fix feature in locked conversation

### PR DESCRIPTION
**Pull request by kovsu**
Close: #8081 

## Test URLs

- PR: https://github.com/refined-github/refined-github/pull/4119
- Locked PR: https://github.com/refined-github/refined-github/pull/975
- Discussion: https://github.com/parcel-bundler/parcel/discussions/6490
- Locked discussion: https://github.com/orgs/community/discussions/28776

## Screenshot

https://github.com/user-attachments/assets/de322477-57bc-46f4-a18b-35d3909a535c

### CODE REVIEW

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/pull/7930#discussion_r1814125443

This might break discussions. Does [`ee7ce12` (#7930)](https://github.com/refined-github/refined-github/pull/7930/commits/ee7ce12babe5ceba6690f5564b0b56b7dd451ddb) need to be reverted?

**Comment by kovsu** [comment]
Maybe we should apply this https://github.com/refined-github/refined-github/pull/7930#discussion_r1812509533

**Comment by fregante** [comment]
> Does [`ee7ce12` (#7930)](https://github.com/refined-github/refined-github/pull/7930/commits/ee7ce12babe5ceba6690f5564b0b56b7dd451ddb) need to be reverted?

Yes this was it, unless this PR works on discussions as is (without errors).

For the record, it seems that locked discussions can still be reacted to. We should add this to the test URLs: https://github.com/orgs/community/discussions/28776

**Comment by fregante** [comment]
> this PR works on discussions as is (without errors).

Did you see any errors on the previous version of this PR? The selector seems to work ok without the last commit.

**Comment by kovsu** [comment]
> Did you see any errors on the previous version of this PR? The selector seems to work ok without the last commit.

It has error if i remove the `enabled`

**Comment by kovsu** [comment]
I update the screenshot with the last code.

**Comment by fregante** [comment]
> > Did you see any errors on the previous version of this PR? The selector seems to work ok without the last commit.
> 
> It has error if i remove the `enabled`. So I revert it and it doesn't.

What error and on what page? I'm running the previous commit and I see no errors on https://github.com/orgs/community/discussions/28776

> We should add this to the test URLs:

By this I generally mean _in the file itself_, for future reference.

**Comment by fregante** [comment]
> What error and on what page? I'm running the previous commit and I see no errors on [github.com/orgs/community/discussions/28776](https://github.com/orgs/community/discussions/28776)
> 
> >

Oh I'm seeing it on https://github.com/orgs/community/discussions/30093, we should add this to the test URLs in the file.

**Comment by kovsu** [comment]
Done

**Comment by fregante** [comment]
I think I know what's happening. GitHub loads a disabled/static version of the reactions and then it replaces it with an enabled/active version that has the `tool-tip` element.

```html
<div
  class="js-comment-reactions-options d-flex flex-items-center flex-row flex-wrap rgh-seen--8573360097"
>
  <button
    name="input[content]"
    id="reactions--reaction_button_component-68cd63"
    value="THUMBS_DOWN react"
    data-button-index-position="1"
    data-reaction-label="-1"
    data-reaction-content="-1"
    aria-pressed="false"
    type="submit"
    disabled="disabled"
    data-view-component="true"
    class="social-reaction-summary-item js-reaction-group-button btn-link d-flex no-underline color-fg-muted flex-items-baseline"
  >
    <g-emoji
      alias="-1"
      fallback-src="https://github.githubassets.com/assets/1f44e-ce91733aae25.png"
      class="social-button-emoji"
      >👎</g-emoji
    >
    <span>3</span>
  </button>
  <button
    name="input[content]"
    id="reactions--reaction_button_component-e6663f"
    value="CONFUSED react"
    data-button-index-position="4"
    data-reaction-label="Confused"
    data-reaction-content="thinking_face"
    aria-pressed="false"
    type="submit"
    disabled="disabled"
    data-view-component="true"
    class="social-reaction-summary-item js-reaction-group-button btn-link d-flex no-underline color-fg-muted flex-items-baseline"
  >
    <g-emoji
      alias="thinking_face"
      fallback-src="https://github.githubassets.com/assets/1f615-4bb1369c4251.png"
      class="social-button-emoji"
      >😕</g-emoji
    >
    <span>1</span>
  </button>
</div>
```

```html
<div
  class="js-comment-reactions-options d-flex flex-items-center flex-row flex-wrap rgh-seen--8573360097"
>
  <button
    name="input[content]"
    id="reactions--reaction_button_component-efbc2d"
    value="THUMBS_DOWN react"
    data-button-index-position="1"
    data-reaction-label="-1"
    data-reaction-content="-1"
    aria-pressed="false"
    aria-label="react with thumbs down"
    type="submit"
    data-view-component="true"
    class="social-reaction-summary-item js-reaction-group-button btn-link d-flex no-underline color-fg-muted flex-items-baseline mr-2"
    aria-describedby="tooltip-b5f4c3ef-506b-4a65-bf00-3f46881ea683"
  >
    <g-emoji
      alias="-1"
      fallback-src="https://github.githubassets.com/assets/1f44e-ce91733aae25.png"
      class="social-button-emoji"
      >👎</g-emoji
    >
    <span class="js-discussion-reaction-group-count">3</span>
    <span class="avatar-user avatar rgh-reactions-avatar p-0 flex-self-center"
      ><img
        src="https://avatars.githubusercontent.com/Googologyer?size=32"
        class="d-block"
        width="16"
        height="16"
        alt="@Googologyer"
        loading="lazy" /></span
    ><span class="avatar-user avatar rgh-reactions-avatar p-0 flex-self-center"
      ><img
        src="https://avatars.githubusercontent.com/VasanthGN?size=32"
        class="d-block"
        width="16"
        height="16"
        alt="@VasanthGN"
        loading="lazy" /></span
    ><span class="avatar-user avatar rgh-reactions-avatar p-0 flex-self-center"
      ><img
        src="https://avatars.githubusercontent.com/u/33871030?s=64&amp;v=4"
        class="d-block"
        width="16"
        height="16"
        alt="@Generalsimus"
        loading="lazy"
    /></span>
  </button>
  <tool-tip
    id="tooltip-b5f4c3ef-506b-4a65-bf00-3f46881ea683"
    for="reactions--reaction_button_component-efbc2d"
    popover="manual"
    data-direction="n"
    data-type="description"
    data-view-component="true"
    class="position-absolute sr-only"
    role="tooltip"
    style="--tool-tip-position-top: 657.515625px; --tool-tip-position-left: 150.57421875px;"
    >Googologyer, VasanthGN, and Generalsimus reacted with thumbs down
    emoji</tool-tip
  >
  <button
    name="input[content]"
    id="reactions--reaction_button_component-338e4a"
    value="CONFUSED react"
    data-button-index-position="4"
    data-reaction-label="Confused"
    data-reaction-content="thinking_face"
    aria-pressed="false"
    aria-label="react with confused"
    type="submit"
    data-view-component="true"
    class="social-reaction-summary-item js-reaction-group-button btn-link d-flex no-underline color-fg-muted flex-items-baseline mr-2"
    aria-describedby="tooltip-87cd2e93-78f1-481a-b2e3-b2432ea6925d"
  >
    <g-emoji
      alias="thinking_face"
      fallback-src="https://github.githubassets.com/assets/1f615-4bb1369c4251.png"
      class="social-button-emoji"
      >😕</g-emoji
    >
    <span class="js-discussion-reaction-group-count">1</span>
    <span class="avatar-user avatar rgh-reactions-avatar p-0 flex-self-center"
      ><img
        src="https://avatars.githubusercontent.com/wrightdoesphotography?size=32"
        class="d-block"
        width="16"
        height="16"
        alt="@wrightdoesphotography"
        loading="lazy"
    /></span>
  </button>
  <tool-tip
    id="tooltip-87cd2e93-78f1-481a-b2e3-b2432ea6925d"
    for="reactions--reaction_button_component-338e4a"
    popover="manual"
    data-direction="n"
    data-type="description"
    data-view-component="true"
    class="sr-only position-absolute"
    role="tooltip"
    >wrightdoesphotography reacted with confused emoji</tool-tip
  >
  <div class="js-reactions-container">
    <details
      class="dropdown details-reset details-overlay d-inline-block js-all-reactions-popover"
      hidden=""
    >
      <summary
        aria-haspopup="true"
        data-view-component="true"
        class="Button--link Button--medium Button"
      >
        <span class="Button-content">
          <span class="Button-label">All reactions</span>
        </span>
      </summary>

      <ul class="dropdown-menu dropdown-menu-se">
        <li
          class="dropdown-item"
          aria-label="Googologyer, VasanthGN, and Generalsimus reacted with thumbs down emoji"
        >
          <g-emoji
            alias="-1"
            fallback-src="https://github.githubassets.com/assets/1f44e-ce91733aae25.png"
            class="social-button-emoji mr-2"
            >👎</g-emoji
          >
          <span>3 reactions</span>
        </li>
        <li
          class="dropdown-item"
          aria-label="wrightdoesphotography reacted with confused emoji"
        >
          <g-emoji
            alias="thinking_face"
            fallback-src="https://github.githubassets.com/assets/1f615-4bb1369c4251.png"
            class="social-button-emoji mr-2"
            >😕</g-emoji
          >
          <span>1 reaction</span>
        </li>
      </ul>
    </details>
  </div>
</div>
```

The way I'd deal with this is by watching specifically the `tool-tip` element in one case `[role=switch]` in the other, because currently the feature is processing a bunch of elements that don't need processing.

I'll try something

**Comment by fregante** [comment]
- Test URLs updated and described
- "temporarily-disabled" buttons excluded from the main observer
- Dropped outdated/unnecessary complexity (4-year-old bug fixes that are no longer needed)
- Kept the `tool-tip` check and turned the lack of it into a proper error. We do not want features that fail silently

I checked all the test URLs and it works everywhere without errors

**Review by fregante — APPROVED** [review]
works for me if it works for you

**Comment by fregante** [comment]
It doesn't work in the new issues 😅

**Comment by fregante** [comment]
Ok we should be good to go.

By the way you can now create branches from this repository. This might help to work on PRs that are not based on old commits

**Pull request merged**
