### PR TITLE
`default-branch-button` - Fix overlap with other components

### PR DESCRIPTION
**Pull request by kovsu**
close: #7223 

## Screenshot

CleanShot 2024-06-12 at 16 46 38@2x

CleanShot 2024-06-12 at 16 46 32@2x

### CODE REVIEW

**Comment by fregante** [comment]
Indeed, I think this won't be possible due to :has(). We've been dealing with performance issues related to it so its usage should be limited.

- https://github.com/refined-github/refined-github/issues/7331#issuecomment-2120464245

**Comment by kovsu** [comment]
So just use `#StickyHeader` ?

**Comment by kovsu** [comment]
image

image

How about doing it this way? And it seems like this style only needs to be added on the `isSingleFile` page.

image

**Comment by fregante** [comment]
I think that's fine 👍

**Review by fregante — APPROVED** [review]

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
If you'd like, it'd be great to make the same change to `list-prs-for-file` to avoid having to use `:has` as well.

**Pull request merged**
