### PR TITLE
Fix styles of `table-input` and `collapsible-content-button`

### LINKED ISSUE #5392: The style of custom editor buttons is broken
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button can be found at the bottom of the options page.

### Example URLs

https://togithub.com/refined-github/sandbox/issues/3

### Extension version

22.2.1

### Browser(s) used

Firefox

### Description

image

Affected features:
- `table-input`
- `collapsible-content-button`

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5392 

## Test URLs

Any page with a comment form

## Screenshots

<table>
<tr>
	<th>

Before
	<th>

After
<tr>
	<td>

before
	<td>

after

<tr>
	<td></td>
	<td>

On mobile:
after-mobile
</table>

### CODE REVIEW

**Review by cheap-glitch — COMMENTED** [review]
The table icon is bigger than the checklist one by two pixels. My brain is displeased :grimacing:

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Can you also hotfix it a bit? It doesn't have to be perfect

**Comment by cheap-glitch** [comment]
> Can you also hotfix it a bit? It doesn't have to be perfect

Already did, in 9dc4ff31a69075bd0342ddb85b3a75af6086c790 and 786107f347e55c4ffdfa123ff9978b5b8569201a.

After clearing the cache it fixed it for me. Are you still seeing the broken buttons in your browser?

**Comment by fregante** [comment]
> Are you still seeing the broken buttons in your browser?

Yes, but keep in mind that Safari is always behind, so hotfixes need to be applied to all the latest versions in the store


[link-chrome]: https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf 'Version published on Chrome Web Store'
[link-firefox]: https://addons.mozilla.org/firefox/addon/refined-github-/ 'Version published on Mozilla Add-ons'
[link-safari]: https://apps.apple.com/app/id1519867270 'Version published on the Mac App Store'

[Chrome][link-chrome] [][link-chrome] 

[Firefox][link-firefox] [][link-firefox]

[Safari][link-safari] [][link-safari]

**Pull request merged**
