### PR TITLE
`conversation-links-on-repo-lists` - Improve AJAX support

### PR DESCRIPTION
**Pull request by gxr404**
Closes https://github.com/refined-github/refined-github/issues/7520

### Bug1:  It should not be displayed in search "code" panel 

1. open [github.com/search?q=%22webext%22&type=repositories](https://github.com/search?q=%22webext%22&type=repositories)
2. Click "Code" in the sidebar
3. Notice extra links
4. Refresh the page
5. The links are gone

### Bug2: Refresh the page from  search "code" panel , but it does not display after clicking "repositories"

1. open [github.com/search?q=%22webext%22&type=code](https://github.com/search?q=%22webext%22&type=code)
2. Click "Repositories" in the sidebar
3. The links are gone
4. Refresh the page
5.  links show

## Screenshot

Before:

before 

After: 

after
|

### CODE REVIEW

**Comment by fregante** [comment]
Thanks for the PR, but I suggested something different in the original issue: I'd rather make the CSS selector stricter so that it doesn't select those items at all. Is it possible?

**Comment by fregante** [comment]
Technically the feature doesn't work at all because the page has changed, so the selector definitely needs to be updated

https://github.com/search?q=x&type=repositories

Screenshot

**Comment by gxr404** [comment]
sorry，Does “CSS selector stricter” refer to the observer there?

Since clicking from "code" page to "repositories" page does not refresh and only changes the dom,  `include` cannot add `repositories` as a judgment criterion

The dom of "repositories" page is similar to the dom of other search results

If solved from the selector level,  `observer`needs to be changed to `observe('[data-testid="results-list"] > div > div > div > h3 .search-title a', ....` in order to accurately select "repositories" page DOM
Is this acceptable？

**Comment by fregante** [comment]
> Technically the feature doesn't work at all

Actually not entirely true, the feature works but only when the user lands on the specific repo search page. This is definitely an AJAX issue:

- #6554 



> sorry，Does “CSS selector stricter” refer to the observer there?

Yes:

https://github.com/refined-github/refined-github/blob/e33a312b6bbbd52536e7a64860a4e82fd984d100/source/features/conversation-links-on-repo-lists.tsx#L77

**Review by fregante — APPROVED** [review]
I think your changes actually fix both issues

**Pull request merged**
