### PR TITLE
Fix console errors in PR merging box features

### LINKED ISSUE #5547: Console errors in PR-related features
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/sandbox/pull/4

### Extension version

22.3.18

### Browser(s) used

Firefox

### Description

1. Go to an open PR (e.g. https://togithub.com/refined-github/sandbox/pull/4)
2. Open the merging box
3. Click cancel
4. Reload the page, sit back, and enjoy the console errors:

```
❌ clear-pr-merge-commit-message refined-github.js:3007:17
📕 22.3.18 → TypeError: messageField is undefined
    init moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:8622
    runFeature moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:3044
    sessionResumeHandler moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:6003
refined-github.js:3007:43

❌ suggest-commit-title-limit refined-github.js:3007:17
📕 22.3.18 → TypeError: inputField is undefined
    validateInput moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:7481
    runFeature moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:3044
    sessionResumeHandler moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:6003
refined-github.js:3007:43

TypeError: textarea is undefined refined-github.js:6921:7

❌ clear-pr-merge-commit-message refined-github.js:3007:17
📕 22.3.18 → TypeError: messageField is undefined
    init moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:8622
    runFeature moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:3044
    sessionResumeHandler moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:6003
refined-github.js:3007:43

❌ suggest-commit-title-limit refined-github.js:3007:17
📕 22.3.18 → TypeError: inputField is undefined
    validateInput moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:7481
    runFeature moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:3044
    sessionResumeHandler moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/refined-github.js:6003
refined-github.js:3007:43

TypeError: textarea is undefined refined-github.js:6921:7
```

The culprit:
https://github.com/refined-github/refined-github/blob/1903d6e8caee1f82f0bc1ff2b15bb15462294a98/source/github-events/on-pr-merge-panel-open.ts?rgh-link-date=2022-03-24T11%3A39%3A01Z#L20

Not only is this event fired several times during the reloading of the page, but most of those times are _before_ the merge box is even loaded.

I suggest dropping this and renaming the listener `onPrMergePanelToggle` (because it's triggered _every time_ the merge panel is opened, not just the first).

If we really need to react to the _initial_ load of the merge box, we can listen to its `include-fragment` instead.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #5547 

## Test URLs

1. Click on the merge button at the bottom of the page
2. Click on "Cancel" and reload the page
3. No console errors should be produced

## Screenshots

See the review comments below.

### CODE REVIEW

**Review by cheap-glitch — COMMENTED** [review]
This PR drops the `session:resume` listener used in `onPrMergePanelOpen` because of its unreliability (see linked issue for details), and adds two extra listeners to allow for more granularity in each feature:

- `onPrMergePanelOpen` now reacts only to the opening of the merge panel (i.e. when clicking on one of the green Merge buttons).
- `onPrMergePanelLoad` reacts to the initial loading of the merge panel, but in a more reliable way. This is a feature of GitHub that directly show the merge field on page load _iff any of their content have been modified from the defaults_. 
- `onPrCommitMessageRestore` is built on the previous listener and is triggered when GitHub restores the modified contents of the merge fields.

**Comment by cheap-glitch** [comment]
Two related comments that can't be reviews because the files haven't been touched :point_down: 

-----

In `clear-pr-merge-commit-message`, we only need to react to the user opening the panel: when the PR conversation page is first opened, the panel will always be closed, so the user _has_ to open it at least once before merging.

Then on subsequent reloads, any changes the feature made to the commit description will automatically be restored by GitHub.

-----

The `session:resume` event is also used in `prevent-pr-merge-panel-opening`. Since this feature doesn't produce any errors because of it, and because it can be triggered several times with little cost, I haven't touched upon it in this PR.

But it's somewhat unreliable, so it will have to be revised too.

**Comment by fregante** [comment]
The demo videos look good. It would be good to outline the specific situations that our listeners cover, including past fixes we applied, so that we can use it as a test checklist. For example:

- Clean PR load, open merge box
- Clean PR load, open merge box, edit commit title
- Clean PR load, open merge box, edit commit title, reload
- Clean PR load, open merge box, new commit comes in
- ...etc

Or simply list all the "events" that affect the box, like:

- opening and closing it
- loading the page after editing
- etc

**Comment by fregante** [comment]
This PR can be merged after 22.4.1 as is, though

**Comment by cheap-glitch** [comment]
> The demo videos look good. It would be good to outline the specific situations that our listeners cover, including past fixes we applied, so that we can use it as a test checklist.

+1

Actually, I've been thinking that we could really use a permanent list of testing URLs for often-modified features or features that have a lot of edge cases (e.g. `clean-repo-sidebebar`, `clean-conversation-headers`, etc.), so we don't have to go fishing through old PRs for them.

Just a Markdown file somewhere in the repo would be good enough.

**Comment by fregante** [comment]
We can include these details in the feature itself. Adding large comments isn't an issue, we can append them to the file, so they follow the init

**Pull request merged**
