### PR TITLE
Add review status in pr list pages

### PR DESCRIPTION
**Pull request by jdeniau**
In PR list, it's quite difficult to know if we already reviewed the PR, and if it has a request change.

I added the `viewer-review-status` to add a small icon indicating the current user review status on the PR.

It does require a personal token in the extension though.

## Test URLs

https://github.com/pulls
https://github.com/refined-github/sandbox/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen

## Screenshot

Screenshot 2024-08-29 121736

I tried with grey color too, but as PR status do use color, I preferred being consistent:

Screenshot 2024-08-29 120724

### CODE REVIEW

**Comment by fregante** [comment]
How is this different from the text right next to it?

Screenshot 4

**Comment by jdeniau** [comment]
@fregante the text next to it gives an overall information on the PR reviews, but it does not mean that **you** personally reviewed the PR, and if you did, it does not mean that the "changes requested" is from you.
In the #5103 for example, the approval is not from me (I did comment, but did not approve).

**Comment by jdeniau** [comment]
For the record, the failing test in because "there is no screenshot in the readme", but it does. 
The url seems really weird though (with a token or something like that). I did not manage to upload the file on github without token 🤔

**Comment by fregante** [comment]
I think it's best to use https://github.com/pulls/review-requested directly. GitHub also offers this view on each specific repo:

Screenshot

Closing as a near-duplicate of https://github.com/refined-github/refined-github/issues/6202

**Comment by fregante** [comment]
> For the record, the failing test in because "there is no screenshot in the readme", but it does.

When you drop a file on GitHub it'll give you a URL that includes `/refined-github/refined-github/assets/`, you can use that instead of the final URL with a token

**Comment by jdeniau** [comment]
OK I didn't know this view.

For the record, when you are in a team, the first team member that review a PR will review the PR "on behalf of the team", and the PR will not be shown in this view anymore.
I think it's more a github issue (the fact that my colleague did approve a PR does not mean that I do too).

I understand your point of closing this 👍

**Pull request closed without merging**
