### PR TITLE
Exclude comments with links in `hide-low-quality-comments` 

### PR DESCRIPTION
**Pull request by ambarvm**
https://github.com/refined-github/refined-github/issues/5257

## Test URLs
https://github.com/ambarvm/ng-action-test/issues/1

## Screenshot
image

### CODE REVIEW

**Review by fregante — APPROVED** [review]
Excellent, thanks!

**Review by cheap-glitch — APPROVED** [review]
Aah, I just realized the test I added in [`c400478` (#5363)](https://github.com/refined-github/refined-github/pull/5363/commits/c400478164f6ccb29b9413f36c4c61dfeda051e8) was pointless, because we don't have access to the raw Markdown text of the comment anyway.

This is the proper fix.

**Comment by fregante** [comment]
> I just realized the test I added in [`c400478` (#5363)](https://github.com/refined-github/refined-github/pull/5363/commits/c400478164f6ccb29b9413f36c4c61dfeda051e8) was pointless

So we should drop it here

**Comment by cheap-glitch** [comment]
> So we should drop it here

No need, I reverted it by accident in [`47b8d70` (#5363)](https://github.com/refined-github/refined-github/pull/5363/commits/47b8d702263205b5256b725646ac10d223878362), so it didn't make it into the PR in the end :smile:

**Pull request merged**
