### PR TITLE
Hide badges in repo headers and pinned repo cards

### LINKED ISSUE #4767: Hide the "Public" repo badge
### Description

Hide the "Public" repo badge in profile page, repo list and repo page. It seems like it's recently added to GitHub but I think it's a little distractive and I prefer old behaviour, which is only shows private and archived badge.

### Screenshot

- [Profile page](https://github.com/sindresorhus)

- [Repo list](https://github.com/sindresorhus?tab=repositories&type=source)

- [Repo page](https://github.com/sindresorhus/refined-github)

### Example URL

- Profile page: https://github.com/sindresorhus
- Repo list: https://github.com/sindresorhus?tab=repositories&type=source
- Repo page: https://github.com/sindresorhus/refined-github

### PR DESCRIPTION
**Pull request by cheap-glitch**
Resolves #4767 

## Test URLs

 * [Repo home](https://github.com/refined-github/refined-github)
 * [User pinned repos](https://github.com/fregante)
 * [User repo list](https://github.com/fregante?tab=repositories)
 * [Organization pinned repos & repo list](https://github.com/refined-github?type=source)

## Screenshot

<table>
<tr>
	<td>
	<td>Before
	<td>After
<tr>
	<td>Repo title
	<td>

screenshot-1638202650
	<td>

screenshot-1638202662
<tr>
	<td>Pinned repos
	<td>

screenshot-1638202618
	<td>

screenshot-1638202551
</table>

### CODE REVIEW

**Comment by fregante** [comment]
My arguments only applied to the repository title. Public/private/fork does not appear anywhere else in the repo list for example. I think we can't drop _those_

**Comment by kidonng** [comment]
GitHub has these classes for repositories in a list: `.public` / `.private`, `.source` / `.fork`, `.archived`. Template repositories don't have a corresponding class though.

**Comment by kidonng** [comment]
I just had an idea... what if we turn the label in list items into icons, just like the one in repo header? It's more consistent and cleaner than just doing nothing.

**Comment by fregante** [comment]
I don’t think it's worth the extra code that that'd require. Textual labels aren't *that* bad, it's just that in some cases they show duplicate information.

**Review by fregante — APPROVED** [review]
_okaaay let's [goooo](https://www.tiktok.com/@xkypher_21/video/7032357929550368046)_

**Comment by WEGFan** [comment]
Will this have a feature switch instead of applied globally?

**Comment by cheap-glitch** [comment]
> Will this have a feature switch instead of applied globally?

We can easily make it togglable, I personally don't mind

**Comment by nick-f** [comment]
I'd be keen for a toggle as well. There's not an easy way to distinguish between private and internal now.

I had a good couple of minutes of panic when that pill was missing and a repo I thought was meant to be private was public. Thankfully it was private, as intended, and I was able to learn about the repo icon next to the title 😄

**Comment by cheap-glitch** [comment]
> > Will this have a feature switch instead of applied globally?
> 
> We can easily make it togglable, I personally don't mind

@fregante wdyt?

**Pull request merged**
