### PR TITLE
Make 2 CSS features disableable

### LINKED ISSUE #6101: Make more CSS features disableable
We have a few controversial CSS features that we can make disableable. Any preferences? Examples:

- https://github.com/refined-github/refined-github/blob/ebfb5f62b9f92a677402ffe9d61d9c1eee27824c/source/features/scrollable-code-and-blockquote.css
- https://github.com/refined-github/refined-github/blob/ebfb5f62b9f92a677402ffe9d61d9c1eee27824c/source/features/hide-watch-and-fork-count.css

### PR DESCRIPTION
**Pull request by shogohida**
Closes #6101 

## Test URLs
Sorry but I don't know on which pages theses CSS features are used...

### CODE REVIEW

**Comment by fregante** [comment]
Hi, that's not how it works. See how other CSS features do it first

**Comment by shogohida** [comment]
@fregante 
Thanks for your comment! I realized that I need to create tsx files like [this](https://github.com/refined-github/refined-github/blob/ebfb5f62b9f92a677402ffe9d61d9c1eee27824c/source/features/clean-dashboard.tsx) after I created this pull request. I keep it draft until it's ready for review.

**Comment by fregante** [comment]
That's correct. Also the CSS files are already imported in the refined-github.ts file, they need to be removed

**Comment by fregante** [comment]
Feel free to leave a comment after finalizing your changes and testing the extension locally, so we can reopen the PR

**Comment by shogohida** [comment]
I'm so sorry for not being able to spend time to solve the issue 🙏 I will leave a comment as you said if I finish.

**Pull request closed without merging**
