### PR TITLE
Fix handling of "Code" button in `clean-repo-filelist-actions`

### PR DESCRIPTION
**Pull request by cheap-glitch**
## Test URLs
 
 * https://github.com/refined-github/refined-github
 * https://github.com/fregante/browser-extension-template

## Screenshot

**Before**

screenshot-1636999170

**After**
screenshot-1636999150

_In repo templates:_

screenshot-1636999197

### CODE REVIEW

**Comment by kidonng** [comment]
I don't see the issue though:

https://github.com/refined-github/refined-github:
image
https://github.com/fregante/browser-extension-template:
image

**Comment by cheap-glitch** [comment]
Weird. A/B testing probably?

**Comment by kidonng** [comment]
https://github.com/fregante/browser-extension-template markup on my browser:
截屏2021-11-16 19 16 34

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
> Weird, I definitely have a "Code" label still. A/B testing probably?

I do also see the bar correctly in both repos. Maybe we can wait a bit longer

**Comment by fregante** [comment]
@cheap-glitch is this still an issue for you? Both repos still work fine for me

**Comment by cheap-glitch** [comment]
Yes I still see this on every repo, whether I own it or not.

image

@refined-github/maintainers am I the only one seeing this ↑ on repo homepages?

**Comment by yakov116** [comment]
I see code just like @cheap-glitch

**Review by fregante — CHANGES_REQUESTED** [review]
This is what I see with this PR

Screen Shot

**Comment by fregante** [comment]
Does this look the same for you?

Screen Shot 1

**Comment by fregante** [comment]
If you're still having this issue, the code must be adjusted to work in both situations

**Comment by cheap-glitch** [comment]
> Does this look the same for you? I used both GitHub Desktop and Codespaces, for the record.

I don't use Codespaces, I guess that's the difference. I don't even have tabs in that dropdown:

image

> If you're still having this issue, the code must be adjusted to work in both situations

Could you please paste the DOM of the dropdown you have so I can see the differences? Thanks.

**Comment by fregante** [comment]
> > If you're still having this issue, the code must be adjusted to work in both situations
> 
> Could you please paste the DOM of the dropdown you have so I can see the differences? Thanks.

https://gist.github.com/fregante/e854933afd9f4be7a10cbb97c5a2db99

That's what I have minus some hidden `input`s

**Review by fregante — APPROVED** [review]
Screen Shot 1

**Pull request merged**
