### PR TITLE
Improve `forked-to` style

### PR DESCRIPTION
**Pull request by kidonng**
- Drop unused styles
- Vertically align icon
- Update to GitHub's new list style (refer to the native issue filter dropdown)
- Changed "external link" icon to ~~"right arrow" icon, inspired by "Explore more" on dashboard~~ chevron right icon

  image

   Reasons:

  - It is not an external link
  - Even GitHub does not use the "external link" icon all the time
 
    image

## Test URLs

Visit your forks at `https://github.com/<username>?tab=repositories&q=&type=fork`

## Screenshot

<table>
<tr>
	<td><strong>Before</strong>
	<td><strong>After</strong>
<tr>
	<td>
	<td>
<tr>
	<td>
	<td>

### CODE REVIEW

**Comment by fregante** [comment]
I'm ok with the changes and it can be merged today, I'm not too sure about the arrow though since it almost points to the stars. Maybe the link icon?

**Comment by kidonng** [comment]
How about https://primer.style/octicons/chevron-right-16? It's also an arrow but less prominent, and we are already using `chevron-left` in `default-branch-button`.

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
First to see this message, release the kraken!

**Comment by fregante** [comment]
I had to release it myself 🤷‍♂️

**Pull request merged**
