### PR TITLE
Meta: Simplify GitHubFileURL

### PR DESCRIPTION
**Pull request by fregante**
- Reverts https://github.com/refined-github/refined-github/pull/3208
- Renames the class for clarity

Context:

- https://github.com/refined-github/refined-github/issues/6000#issuecomment-1542347775
- https://github.com/refined-github/refined-github/pull/6797#discussion_r1280789513

cc @134130

### CODE REVIEW

**Comment by yakov116** [comment]
I would like to test this, I will try to get to my computer tonight

**Comment by fregante** [comment]
@yakov116 ping

**Comment by yakov116** [comment]
Sorry i will try to do it in a few hours

**Comment by yakov116** [comment]
Looks like i will not have time, sorry

**Comment by fregante** [comment]
I ended up testing it myself and… in Firefox it fails silently. 🤷‍♂️ 

Repro:

1. Open https://github.com/refined-github/refined-github/tree/async-detections
2. Look at `default-branch-button`, the URL is incorrect

Screenshot 2

**Comment by 134130** [comment]
Can we make some CI tests with puppeteer-like testing framework?
Enable all features, visit all given test urls, make sure there is no failed rgh-features.

**Comment by fregante** [comment]
Oof, good luck. Loading extensions in those environments is a pain, especially so in Firefox. Then nobody will add tests. 😅

**Comment by 134130** [comment]
🥲🥲 Also, It'll be annoying when CI test ran on PR of A feature changes, but failing with B feature.
It breaks the pull request order and requires consideration of the merge queue.
🤯😟

**Pull request closed without merging**
