### PR TITLE
Meta: Add link checker

### PR DESCRIPTION
**Pull request by fregante**
- Blocked by https://github.com/lycheeverse/lychee-action/issues/60

### CODE REVIEW

**Comment by kidonng** [comment]
Most links in this repository points to GitHub which probably lives longer than me, but welcoming though. (Also, nice choice of lychee)

**Comment by fregante** [comment]
Yeah in reality we probably don't need this. It'd be good if it also threw errors in case of redirects and we added it to JS and CSS files. I haven't added those because I was testing https://github.com/lycheeverse/lychee-action/issues/60

**Comment by mre** [comment]
> Error: Compiled regex exceeds size limit of 10485760 bytes.

But why?

**Comment by fregante** [comment]
I suppose it's the many globs? I don't know what's inside the tool

**Comment by mre** [comment]
Ah okay I see what's going on. It's a little funny. 😆 
You use `--exclude-file`, which is not what you think it means.
It's meant as a newline-separated list of regular expressions for filtering out links.
So lychee interpreted that file as one huge regex. 😆 
You meant to exclude the file from checking completely.

I think the wording is a bit misleading. 
Your interpretation makes a lot of sense to me so I created 
https://github.com/lycheeverse/lychee/issues/418 
to handle that in the future.

In the meantime there is no way to exclude the file -- just the links within with a regex.
This will be possible with either https://github.com/lycheeverse/lychee/issues/418 or https://github.com/lycheeverse/lychee/issues/284.

**Comment by mre** [comment]
On top of that your repo also triggers https://github.com/seanmonstar/reqwest/issues/668 in reqwest. 😆 

```
refined-github ❯❯❯ lychee --verbose --no-progress -- '**/*.md' '**/*.html' '**/*.css' '**/*.ts' '**/*.tsx'
thread 'tokio-runtime-worker' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /Users/mendler/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.7/src/into_url.rs:70:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Cannot send request: SendError(Ok(Request { uri: Uri { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("${repository.textcontent!.trim()}")), port: None, path: "/", query: None, fragment: None } }, source: FsPath("source/features/link-to-github-io.tsx") }))', lychee-bin/src/commands/check.rs:80:14
```

Created a PR to fix that: https://github.com/seanmonstar/reqwest/pull/1399. 🤞 
It helps find bugs when testing lychee on bigger repos, so thanks for that. 😊

**Comment by fregante** [comment]
> In the meantime there is no way to exclude the file

Gotcha, thanks! I think I'll pass for now then.

**Pull request closed without merging**
