### PR TITLE
Meta: Update some feature screenshots

### PR DESCRIPTION
**Pull request by kidonng**
# A screenshot a day keeps the cruft away

https://github.com/refined-github/refined-github/issues/5222#issuecomment-996620545

See each individual commit for details.

Your help is needed since I'm probably not going to finish this alone 😛

### CODE REVIEW

**Comment by fregante** [comment]
> Your help is needed since I'm probably not going to finish this alone 😛

Commit, merge, repeat. We don't have to replace them all at once, do what you feel like and merge

**Comment by cheap-glitch** [comment]
`bugs-tab`

bugs-tab

`one-click-diff-options`

one-click-diff-options

**Comment by cheap-glitch** [comment]
I'd like to do those two and then we can merge this:

- [ ] `download-folder-button`
- [ ] `first-published-tag`

**Review by yakov116 — APPROVED** [review]
LGTM

**Comment by fregante** [comment]
I'll merge this before the next release

**Comment by fregante** [comment]
Feel free to reopen when new screenshots are taken.

It'd be great to see them in comments here like @cheap-glitch did since you need to upload them anyway

**Pull request merged**
