### PR TITLE
Fix duplication in `comment-on-draft-pr-indicator`

### LINKED ISSUE #5191: Comment on draft PR on draft PR on draft PR on draft PR
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

### Description

`comment-on-draft-pr-indicator`’s deduplication is failing

Screen Shot 5

1. Open https://github.com/refined-github/refined-github/pull/5090#issuecomment-971465633
2. Click "Follow up to XXX (comment)" link in first post
3. Go back
4. Scroll down

### Example URL

https://github.com/refined-github/refined-github/pull/5090

### Browser(s) used

Safari

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fix #5191 

## Test URLs

 1. Go to https://togithub.com/refined-github/sandbox/pull/7
 2. Click on the "Open issue" link in the sidebar
 3. Go back
 4. The text in the comment button should not be duplicated

## Screenshot

https://user-images.githubusercontent.com/46634000/145685950-4ab3e8d2-b7d8-469d-a742-af8b2058cf8b.mp4

### CODE REVIEW

**Review by cheap-glitch — COMMENTED** [review]
Couldn't reproduce this with review comment buttons, so I left those out of the de-duplication.

**Review by fregante — APPROVED** [review]
Tested, confirmed to work

**Comment by cheap-glitch** [comment]
Wow that was fast :open_mouth:

**Comment by fregante** [comment]
Faster push, review, merge loop ever!

**Comment by fregante** [comment]
I saw the PR with "Opened 27 seconds ago" 😂

**Pull request merged**
