### PR TITLE
Update dependencies 

### PR DESCRIPTION
**Pull request by yakov116**
## Test URLs
None

## Screenshot
None

Small change due to https://github.com/moh3n9595/js-abbreviation-number/commit/979f3c1054c56cc10b1e4d3eedf91249796381ba

The k is lowercase (When a repo has one million bug issues we can revert this change)

### CODE REVIEW

**Comment by fregante** [comment]
I just updated them 10 days ago after months of no updates 🤷‍♂️ I don't see the need right now https://github.com/refined-github/refined-github/pull/5265

**Comment by yakov116** [comment]
This PR was not supposed to end here. No worries

**Comment by fregante** [comment]
> This PR was not supposed to end here

What else was supposed to be in here exactly? I don't see any other updates available

**Comment by yakov116** [comment]
I was going to make a lint in it too. It's OK , there is another lint open and I got very busy.

No worries it was OK to close.

**Comment by fregante** [comment]
By the way you or Kidonng can bring that code change to the open lint PR

**Pull request closed without merging**
