### PR TITLE
Less eye-catching `rgh-netiquette`

### LINKED ISSUE #6484: Make `rgh-netiquette` less eye-catching
I think this is a bit much:

Screenshot 18

It should roughly match the visual weight of the comment box. Maybe it should be gray or just not a banner at all.

### Test URL

https://github.com/refined-github/sandbox/pull/17
https://github.com/refined-github/sandbox/pull/1

### PR DESCRIPTION
**Pull request by fregante**
- fixes #6484 

## Test URLs

https://github.com/refined-github/sandbox/pull/17
https://github.com/refined-github/sandbox/pull/1

## Before

Screenshot 25

## After

Screenshot 24

### Dark

Screenshot 26

### CODE REVIEW

**Comment by fregante** [comment]
I think this does its job well:

- makes the issue look like it's locked
- anyone looking for the comment box, will find a reasonably-visible and large message
- anyone just visiting won't be bothered just body text with a thin light border

**Comment by kidonng** [comment]
> * anyone looking for the comment box, will find a reasonably-visible and large message

Isn't that enough to leave out the border? Looks weird to me.

**Comment by fregante** [comment]
It needs to fit in with the other boxes, also notice how GitHub does the same (border-ony) with their first box

Screenshot 28

The only inconsistency here is the info icon 😳

**Comment by fregante** [comment]
Merging this for now before the release, we can discuss further improvements separately

**Pull request merged**
