### PR TITLE
`status-subscription` - Improve contrast

### PR DESCRIPTION
**Pull request by kovsu**
Close: #7800 

## Test URLs

https://github.com/refined-github/refined-github/issues/7800

## Screenshot

image

image

### CODE REVIEW

**Comment by fregante** [comment]
How about the border like in your earlier screenshot?

**Comment by kovsu** [comment]
@fregante I think the boreder maybe we don't need now. I think it is distracting if we add the border.

**Comment by fregante** [comment]
I think the contrast here is still too low, especially when the middle one is selected in dark mode. A slightly stronger border would definitely help.

**Comment by kovsu** [comment]
Actually I just want to notice it when I look at the notifications, not when I enter the page.

**Comment by fregante** [comment]
Yes I'm not talking about the blue border but just a brighter/darker one. As is, there's not much improvement over the current one

**Comment by fregante** [comment]
Screenshot 8


Screenshot 9

**Comment by kovsu** [comment]
@fregante I'm just working on it. 😂

image

**Comment by fregante** [comment]
too late haha, I wanted to release a new version 😁

**Pull request merged**
