### PR TITLE
Fix alignment of "Code of conduct" link in `clean-repo-sidebar`

### PR DESCRIPTION
**Pull request by cheap-glitch**
## Test URLs

https://github.com/sindresorhus/got

## Screenshot

**Before**

screenshot-1637498668

**After**

screenshot-1637498654

### CODE REVIEW

**Review by cheap-glitch — COMMENTED** [review]
Alternatively, we could stop removing the extra whitespace before the license link, and _add_ some to the repo age (easy) and the latest release tag (tricky).

**Comment by fregante** [comment]
This looks ok. What we want is the path that requires the least code while being consistent (i.e. no hacks like "let's add a negative margin of 0.3em because that's the width of a space on my computer")

**Comment by fregante** [comment]
Honestly I'd just remove it. The CoC is basically just a "don't be a dick" and that's something people do or don't do regardless of CoCs

**Comment by cheap-glitch** [comment]
> Honestly I'd just remove it. The CoC is basically just a "don't be a dick" and that's something people do or don't do regardless of CoCs

I don't mind removing the new "Code of conduct" link in the repo sidebar, but some might be against it.

cc @sindresorhus  @refined-github/maintainers any thoughts?

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Ooops, I had approved my changes, which I was extracting into their own PR.

**Pull request merged**
